-- +goose Up

-- Add source column to distinguish auto-computed vs user-added line items.
-- AUTO = generated by settlement computation (readonly on frontend)
-- MANUAL = added by user (editable on frontend)
ALTER TABLE bill_line_items
  ADD COLUMN source VARCHAR(10) NOT NULL DEFAULT 'AUTO'
    CHECK (source IN ('AUTO', 'MANUAL'));

-- Add updated_at for tracking manual item edits.
ALTER TABLE bill_line_items
  ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- +goose Down

ALTER TABLE bill_line_items DROP COLUMN IF EXISTS updated_at;
ALTER TABLE bill_line_items DROP COLUMN IF EXISTS source;
